version: "3"
services:
  app:
    build: .
    ports:
      - 3001:3001
    links:
      - mongo
    volumes:
      - "./app:/app"
    command: npm run start:dev
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
